version: "3.9"

services:
  todo_mongo:
    container_name: todo_mongo_container
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27018:27017"
    logging:
      driver: none
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI=mongodb: mongodb://mongo_db:27017 
      DB_NAME: my_db
      NAME: trefu
    depends_on:
      - todo_mongo

volumes:
  mongo_db: {}